blank_issues_enabled: false
contact_links:
  - name: Startrack Community Discussions
    url: https://github.com/ashish102312/startrack/discussions
    about: Ask questions and discuss features with the community.
